### ISSUE TITLE
Form the error package structure, and reflect it in the documentation

### ISSUE THREAD

**Issue by radomir9720** [starfactorypixel/MainECU#8]
It is expected that the error package structure will be like the regular package structure, except the request type(it should be __0x1E__).
For handling these errors and use the data from error package on L3 device(e.g. to show to the user the error reason, or write the error code to crashlytics, etc.), we must know what kind of data should be in the package.
So the tasks are to think about, implement, and reflect in the documentation: 
1. What kinds of errors can appear in the process of work
2. How to identify the error(i.e. give some id)
3. What data should contain the package with specific error.

Blocking radomir9720/pixel_app_flutter#19

**Comment by Dragon-Knight** [comment]
На данный момент не могу сказать ни о структуре ни о типах ошибок.
Пока предполагаю что тип _0x1E_ будет иметь вложенный пакет, где будет описан код ошибки, связный с текущим ID и динамическое поле произвольной длины для доп. параметров.

**Comment by radomir9720** [comment]
Так я и не просил ответ прямо сейчас)) Когда появится структура, тогда появится.

**Comment by radomir9720** [comment]
Реализовано: https://docs.google.com/spreadsheets/d/1rOYpiT1S05CxcOVvX0OtkjVuEJVvVVoyuHM8ffLTHoA/edit#gid=118036148
